#For Color Codes you can look here: https://minecraft.fandom.com/wiki/Formatting_codes
#For color gradients look here: https://rgb.birdflop.com
#Only Use Color Codes from the Websites! Other Color Codes don't work.

Language: en #Available Languages are 'en' = English and 'de' = Deutsch

#Variables <- Not used yet!
ServerName: A Minecraft Server
DiscordInvite: null #Set to null when you don't have a Discord
ServerIP: null #Maybe for coming Features for the Discord Bot, like an IP Command, or a switching Activity with the IP in it.

#Server Start Messages
StartupAnnouncement: true
EventJoinTitle: true

#Join/Quit Message
#Use player for the Player Name
#If there is no indication, there is an error message in the console and the default join message comes
SendJoinMessage: true #This only disable/enable the custom Join Messages from this Plugin and don't deactivate completely the Join Messages!
SendQuitMessage: true #This only disable/enable the custom Quit Messages from this Plugin and don't deactivate completely the Quit Messages!
JoinMessage:
  - §a» §7player
QuitMessage:
  - §c« §7player

#Seed Hider
#Deactivate it under 'CommandBlock -> /seed' in this Config.
SeedColor: §a

CommandBlock: #All Commands have a new Command! A Message with the new Command comes, when the old Command got used and the Player has the Permission for the new Command.
  /seed: true
  /msg: true
  /kick: true
  /pardon: true
  /ban: true

#Spawn Elytra
spawnradius: 50
multiplyValue: 5

#Start Command Actions
worldborderafterstart: 5000000
worldbordergrowtime: 50
StartTitle:
  Top: §x§4§c§3§2§b§d§oY§x§5§5§3§0§b§3§oV§x§5§e§2§e§a§a§o-§x§6§7§2§c§a§0§oS§x§7§0§2§b§9§7§oM§x§7§9§2§9§8§d§oP §x§8§b§2§5§7§a§o#§x§9§4§2§3§7§0§o4
  Bottom: §x§8§e§2§5§7§7§oS§x§8§8§2§6§7§d§ot§x§8§2§2§7§8§3§oa§x§7§c§2§8§8§9§or§x§7§7§2§9§8§f§ot§x§7§1§2§a§9§5§oe§x§6§b§2§c§9§c§ot §x§5§f§2§e§a§8§og§x§5§a§2§f§a§e§ol§x§5§4§3§0§b§4§oe§x§4§e§3§1§b§a§oi§x§4§8§3§2§c§0§oc§x§4§3§3§4§c§6§oh
WhitelistafterStart: true

#MOTD
FakePlayerAllowedToJoinCounter: 0

Players:
  - PlayerName1
  - PlayerName2
  - PlayerName3
  - PlayerName4

MOTD'sText:
  #'player1' For one Player Name and 'player2' for another Player Name. The names will get from the "Players" Config Above.
  Top:
    - MOTD Text 1
    - §aMinecraft §eSMP §cProject
  Bottom:
  - §bplayer1 says hello to player2
  - §eplayer1 goes to MC Donalds
  - §6player1 goes to Burger King
  - §3player1 like player2
  - §5player1 plays on Hypixel
  - §dplayer1 like trains
  - §aplayer1 get killed from player2
  - §7player1 asks for the Map Seed
  - §8player1 wants to get Fame
  - §bSponsored by ...
  - §9Whitelist activated!
  - §csince ...
  - §aStarted at the ??.??.????
  - §dServer is online
  - §4Can't connect to Server
  Mainteance: §cServer is in Mainteance Mode

# How the Direct Message System should be configured
DirectMessage:
  Design: #Design of who sent you the Message. More than one Design is possible! Use 'sender' for Name of the sender and 'receiver' for the Name of the Person who will receive it.
    - §e[§csender §e-> §creceiver§e]§f

#Placeholder
Placeholder:
  PREFIX: §9[YVtils]
  PREFIXSMP: §9[YVtils-SMP]
  PREFIXLOBBY: §9[YVtils-LY]
  PREFIXKICK: §9[YVtils-K]
  PREFIXCONNECT: §9[YVtils-CO]
  PREFIXDISCONNECT: §9[YVtils-DCO]
  PREFIXENABLE: §9[YVtils-ON]
  PREFIXDISABLE: §9[YVtils-OFF]
  PREFIXERROR: §4[YVtils-ERROR]
  PREFIXERELOAD: §9[YVtils-RL]
  PREFIXUPDATE: §c[YVtils-UPDATE]
  PREFIXNOUPDATE: §7[YVtils-UPDATE]
  PREFIXSTART: §9[YVtils-START]
  PREFIXSEED: §9[YVtils-SEED]
  PREFIXANNOUNCEMENT: §4[YVtils-ANNOUNCEMENT]
  PREFIXHELP: §9[YVtils-HELP]
  PREFIXFEEDBACK: §9[YVtils-FEEDBACK]
  PREFIXGLOBALMUTE: §a[YVtils-MUTE]
  PREFIXMODERATION: §c[YVtils-MOD]
  PREFIXDC: §9[YVtils-DC]

#Other Stuff
CustomRecipes: true

#Do not edit!
Debug: false #Only set to true when you know what you're doing, or you need Help and the Support say so!
ConfigVersion: 11