name: YVtils-SMP
version: ${project.version}
main: yv.tils.smp.SMPPlugin
api-version: 1.18
authors: [ WolfiiYV ]
description: Plugin for SMP Server
website: yvnetwork.de

commands:
  start:
    permission: yvtils.smp.command.start
  afkdamage:
    permission: yvtils.smp.command.afkdamage
  mutechat:
    aliases:
      - globalmute
      - chatmute
    permission: yvtils.smp.command.mutechat
  fly:
    permission: yvtils.smp.command.fly
  flywalkspeed:
    permission: yvtils.smp.command.flyspeed
    aliases:
      - flyspeed
      - walkspeed
  moderation:
    permission: yvtils.smp.command.moderation
    aliases:
      - mod
      - admin
  gm:
    permission: yvtils.smp.command.gm
  vanish:
    permission: yvtils.smp.command.vanish
    aliases:
      - v
  directmessage:
    permission: yvtils.smp.command.directmessage
    aliases:
      - dm
  reply:
    permission: yvtils.smp.command.reply
    aliases:
      - r
  god:
    permission: yvtils.smp.command.god
    aliases:
      - godmode
  heal:
    permission: yvtils.smp.command.heal
  maintenance:
    permission: yvtils.smp.command.maintenance
  status:
    permission: yvtils.smp.command.status
    aliases:
      - prefix
      - role
permissions:
  yvtils.smp.play:
    description: Let Player Plays
  yvtils.smp.*:
    description: Allows everything
  yvtils.smp.bypass.mutechat:
    description: Let you write while Chat is muted
  yvtils.smp.command.bypass.seed:
    description: Do not replace the /seed Command
  yvtils.smp.command.moderation.ban.getannounced:
    description: Announcement in Chat when someone get banned
  yvtils.smp.command.moderation.temp.ban.getannounced:
    description: Announcement in Chat when someone get temp banned
  yvtils.smp.command.moderation.kick.getannounced:
    description: Announcement in Chat when someone get kicked
  yvtils.smp.command.moderation.unban.getannounced:
    description: Announcement in Chat when someone get unbanned
  yvtils.smp.command.moderation.ban:
    description: Allow users to ban other Players
  yvtils.smp.command.moderation.temp.ban:
    description: Allow users to tempban other Players
  yvtils.smp.command.moderation.kick:
    description: Allow users to kick other Players
  yvtils.smp.command.moderation.unban:
    description: Allow users to unban other Players
  yvtils.smp.collercodes.chat:
    description: With this Permission Players can use Color Codes in Chat
  yvtils.smp.maintenance.join:
    description: Players with this Permission can Join, when the Maintenance Mode is activated!
  yvtils.smp.command.status.clear.other:
    description: Players with this Permission can clear the Status of other Players
  yvtils.smp.command.status.set:
    description: Players with this Status can set a custom Status
  yvtils.smp.updateannounce:
    description: Send a Message to Players with this Permission, when a Config Update is available or the Language is not available