name: YVtils-BA
version: ${project.version}
main: de.yvtils.ba.Main
api-version: 1.16
authors: [ WolfiiYV ]
description: Plugin for YV-SMP
website: wolfiiyv.de

commands:
  start:
    permission: yvtils.ba.command.start
  testkick:
    permission: yvtils.ba.command.testkick