name: YVtils-BA
version: 4.3.1-ChristmasEdition
main: de.yvtils.ba.Main
api-version: 1.16
authors: [ WolfiiYV ]
description: Plugin for YV-SMP
website: wolfiiyv.de

commands:
  start:
    permission: yvtils.ba.command.start
permissions:
  yvtils.ba.play:
    description: Let Player Plays
  yvtils.ba.*:
    description: Allows everything
  yvtils.ba.advancedcrafting.betterprot:
    description: Craft Better Prot
  yvtils.ba.advancedcrafting.fastertools:
    description: Craft Faster Tools
  yvtils.ba.advancedcrafting.light:
    description: Craft Light Blocks
  yvtils.ba.advancedcrafting.debugstick:
    description: Craft DebugStick
  yvtils.ba.advancedcrafting.*:
    description: Craft Everything Advanced
  yvtils.ba.command.notreplace.seed:
    description: Do not replace the /seed Command


