name: YVtils-SMP
version: 4.4
main: yv.tils.smp.Main
api-version: 1.16
authors: [ WolfiiYV ]
description: Plugin for SMP Server
website: wolfiiyv.de

commands:
  start:
    permission: yvtils.smp.command.start
  afkdamage:
    permission: yvtils.smp.command.afkdamage
  mutechat:
    aliases:
      - globalmute
      - chatmute
    permission: yvtils.smp.command.mutechat
permissions:
  yvtils.smp.play:
    description: Let Player Plays
  yvtils.smp.*:
    description: Allows everything
  yvtils.smp.bypass.mutechat:
    description: Let you write while Chat is muted
  yvtils.smp.advancedcrafting.betterprot:
    description: Craft Better Prot
  yvtils.smp.advancedcrafting.fastertools:
    description: Craft Faster Tools
  yvtils.smp.advancedcrafting.light:
    description: Craft Light Blocks
  yvtils.smp.advancedcrafting.debugstick:
    description: Craft DebugStick
  yvtils.smp.advancedcrafting.*:
    description: Craft Everything Advanced
  yvtils.smp.command.bypass.seed:
    description: Do not replace the /seed Command


